# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

### MAIN SHELL
# directory | username@hostname | cmd duration | sudo | VCS | language versions | kubernetes
# > input after line break
format = """
[](fg:red)\
[](bg:red)\
$directory\
$username\
$hostname\
$container\
$sudo\
$shlvl\
[](fg:red bg:16)\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:16 bg:yellow)\
$cmd_duration\
$status\
[](fg:yellow bg:green)\
$deno\
$golang\
$helm\
$lua\
$nodejs\
$php\
$python\
$rust\
$vagrant\
[](fg:green bg:blue)\
$package\
[](fg:blue bg:purple)\
$aws\
$azure\
$gcloud\
$openstack\
$docker_context\
$kubernetes\
$terraform\
[](fg:purple)\
$line_break\
$shell\
$character"""
add_newline = true

[custom.left]
symbol = ""
style = "fg:bright-purple"
when = true

[custom.right]
symbol = ""
style = "fg:bright-purple"
when = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = 'bg:red fg:#000000'
read_only = ''
use_os_path_sep = false

[username]
format = '[$user]($style)'
style_root = 'bg:red fg:#000000'
style_user = 'bg:red fg:#000000'

[hostname]
format = '[$ssh_symbol$hostname]($style)'
style = 'bg:red fg:#000000'
ssh_symbol = ' '

[container]
format = '[$hostname]($style)'
style = 'bg:red fg:#000000'

[sudo]
disabled = false
format = '[$symbol]($style)'
style = 'bg:red fg:#000000'
symbol = ' '

[shlvl]
style = 'bg:red fg:#000000'

### VCS
[git_branch]
symbol = ' '
format = '[$symbol$branch]($style)'
style = 'bg:16 fg:#000000'

[hg_branch]
format = '[$symbol$branch]($style)'
style = 'bg:16 fg:#000000'

[git_commit]
format = '[\($hash$tag\)]($style)'
tag_disabled = false
tag_symbol = '  '
style = 'bg:16 fg:#000000'

[git_state]
format = '[\($state( $progress_current/$progress_total)\)]($style)'
style = 'bg:16 fg:#000000'

[git_status]
format = '([ $all_status$ahead_behind]($style))'
ahead = "↑"
behind = "↓"
conflicted = "!"
deleted = "×"
diverged = "↕"
modified = "~"
renamed = "»"
untracked = "+"
staged = "●"
stashed = "ﮅ "
style = 'bg:16 fg:#000000'

[cmd_duration]
format = '[ﮫ $duration]($style)'
style = 'bg:yellow fg:#000000'

[status]
style = 'bg:yellow fg:#000000'

### LANGUAGE VERSION INDICATORS
[c]
format = '[ $symbol($version(-$name)) ]($style)'
style = 'bg:green fg:#000000'

[cmake]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[cobol]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[conda]
format = '[ $symbol$environment ]($style)'
style = 'bg:green fg:#000000'

[crystal]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[dart]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[deno]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[dotnet]
format = '[ $symbol($version)( $tfm) ]($style)'
style = 'bg:green fg:#000000'

[elixir]
format = '[ $symbol($version \(OTP $otp_version\)) ]($style)'
style = 'bg:green fg:#000000'

[elm]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[erlang]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[golang]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[haskell]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[helm]
symbol = 'ﴱ '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[java]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[julia]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[kotlin]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[lua]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[nim]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[nix_shell]
format = '[ $symbol$state( \($name\)) ]($style)'
style = 'bg:green fg:#000000'

[nodejs]
symbol = ' '
format = '[ $symbol($version) ]($style)'
detect_extensions = []
style = 'bg:green fg:#000000'

[ocaml]
format = '[ $symbol($version)(\($switch_indicator$switch_name\)) ]($style)'
style = 'bg:green fg:#000000'

[perl]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[php]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[pulumi]
format = '[ $symbol$stack ]($style)'
style = 'bg:green fg:#000000'

[purescript]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[python]
symbol = ' '
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)'
style = 'bg:green fg:#000000'

[red]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[ruby]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[rust]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[scala]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[spack]
format = '[ $symbol$environment ]($style)'
style = 'bg:green fg:#000000'

[swift]
symbol = ' '
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[vagrant]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[vlang]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

[zig]
format = '[ $symbol($version) ]($style)'
style = 'bg:green fg:#000000'

### PACKAGE INDICATORS

[package]
symbol = ' '
format = '[ $symbol$version ]($style)'
style = 'bg:blue fg:#000000'

### CONTEXT INDICATORS
[aws]
symbol = ' '
format = '[ $symbol($profile)(\($region\))(\[$duration\]) ]($style)'
style = 'bg:purple fg:#000000'

[docker_context]
symbol = ' '
format = '[ $symbol$context ]($style)'
style = 'bg:purple fg:#000000'

[gcloud]
symbol = ' '
format = '[ $symbol$account(@$domain)(\($region\)) ]($style)'
style = 'bg:purple fg:#000000'

[kubernetes]
symbol = ' '
format = '[ $symbol($cluster/$namespace) ]($style)'
disabled = false
style = 'bg:purple fg:#000000'

[openstack]
symbol = ' '
format = '[ $symbol$cloud(\($project\)) ]($style)'
style = 'bg:purple fg:#000000'

[terraform]
format = '[ $symbol$workspace ]($style)'
style = 'bg:purple fg:#000000'

### STATUS INDICATORS

[character]
success_symbol = '[ﬦ](bold cyan)'
error_symbol = '[ﬦ](bold red)'
vimcmd_symbol = '[ﬦ](bold cyan)'
